name: Main

on:
    workflow_dispatch:
    pull_request:
    push:
        branches:
            - main
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Check out repo
              uses: actions/checkout@v3
            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                  node-version: 18.12.x

            - name: Install dependencies
              run: yarn install

            - name: Build
              run: yarn build

            - name: Test script
              run: yarn test

            - name: Lint
              run: yarn lint

            - name: Deploy
              uses: SamKirkland/FTP-Deploy-Action@4.3.3
              with:
                  server: ${{ secrets.cripto_coin }}
                  username: ${{ secrets.user }}
                  password: ${{ secrets.password }}
